name: List Files in Repository

on:
  push:
    branches:
      - main
jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in repository
        run: ls -al
